//
//  WaveFunction.swift
//  BasicSynth
//
//  Created by Kfir Breger on 26/09/2026.
//
import Foundation


// typealias WaveFunction = (_ phase: Float, _ harmonics: Int) -> Float

// Using an empty enum as a namespace
nonisolated enum Waveform: String, CaseIterable, Sendable {
    case sine
    case sawtooth
    case square
    case triangle
    case noise
    
    static let twoPi = Float.pi * 2.0
    static let piSq = Float.pi * Float.pi
   
    func sample(phase: Float, harmonics: Int) -> Float {
        switch self {
        case .sine:
            return sin(phase)
            
        case .sawtooth:
            var sample: Float = 0
            for i in 1...harmonics {
                sample += sin(Float(i) * phase) / Float(i)
            }
            return (2.0 / Float.pi) * sample
        case .square:
            var sample: Float = 0
            for i in stride(from: 1, to: harmonics + 1, by: 2) {
                sample += sin(Float(i) * phase) / Float(i)
            }
            return (4.0 / Float.pi) * sample
        case .triangle:
            var sample: Float = 0
            for i in stride(from: 1, to: harmonics + 1, by: 2) {
                sample += powf(-1.0, (Float(i) - 1.0) / 2.0) * sin(Float(i) * phase) / Float((i * i))
            }
            return (8.0 / Waveform.piSq) * sample
        case .noise:
            // The white noise is generated by a noise generator.
            // This should never be reached
            assertionFailure("Noise should be intercepted before sample function call")
        }
    }
}

